Feature/UI interface completion
danielairinei/internship-scooterapp pull request #10
Opened 2022-09-27 07:28 UTC by danielairinei

2022-09-28 05:28 UTC, catadarjan-tapptitude requested changes

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/dto/user/UserApi.kt
> +import retrofit2.http.*
Avoid using `*` imports

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/data/dto/user/UserApi.kt
> +    suspend fun getUser(@Header("Authorization") token: String) : UserDto
Use SessionInterceptor for header token

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_start_ride_bottom_sheet.xml
> +<?xml version="1.0" encoding="utf-8"?>
I'd rename this and `item_scooter_bottom_sheet` to something like `dialog_start_ride` / `dialog_scooter_details`

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_scooter_bottom_sheet.xml
> +        android:layout_marginTop="26dp"
Extract raw dimens

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_history_card_view.xml
> +        android:text="Strada Lunii 2A"
I assume you wanted to use `tools` here for preview? This applies in a couple other places as well

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_history_card_view.xml
> +    android:layout_gravity="center|top"
I think this field is redundant in a CL

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_history_card_view.xml
> +    tools:ignore="ContentDescription,HardcodedText">
Use `ignore` fields only in the specific views where it is necessary. Using it in a parent tag might make you miss some lint warnings inside

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_history_card.xml
> +    android:layout_width="328dp"
Extract raw dimens

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/item_history_card.xml
> +        android:text="Total rides: 12"
I assume you wanted to use `tools` here for preview?

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu_history.xml
> +        <com.google.android.material.appbar.MaterialToolbar
Why do you need to wrap `MaterialToolbar` in an `AppBarLayout`?

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu_history.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Could this layout be simplified to a `LinearLayout`?

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu_history.xml
> +        android:layout_gravity = "center_horizontal"
Remember to periodically format your code

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu_account.xml
> +        android:layout_marginEnd = "84dp"
Extract raw dimens and remember to periodically format your code

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu_account.xml
> +        <com.google.android.material.appbar.MaterialToolbar
I think you could use `MaterialToolbar` by itself w/o wrapping

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu_account.xml
> +    android:orientation="vertical"
Orientation field is redundant in CL

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu.xml
> +    tools:ignore="ContentDescription">
Use `ignore` only in specific views, otherwise you might miss important lint warnings

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_menu.xml
> +    android:layout_marginTop="@dimen/margin_top_toolbar"
Why do you need this marginTop?

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/drawable/bg_history_cardview.xml
> +        android:width="1dp"
Extract raw dimens

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/res/drawable/bg_history_card.xml
> +    <corners android:radius="30dp" />
Extract raw dimens & use specific colors

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/repository/UserRepository.kt
You've got some extra empty lines in this file

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/adapter/RideHistoryItem.kt
> +    val startAddress: String = "Strada Lunii 2A",
Remove mock data default values once you don't need them

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/adapter/RideHistoryAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RideHistoryViewHolder {
Could inline this as 
```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RideHistoryViewHolder =
    RideHistoryViewHolder(ItemHistoryCardViewBinding.inflate(LayoutInflater.from(parent.context), parent, false))
```

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/MenuFragment.kt
> +        binding.toolbar.setNavigationOnClickListener {
I prefer leaving an empty line between setters. It makes the code a bit clearer imo

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/MenuAccountFragment.kt
> +
Extra empty line

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/MenuAccountFragment.kt
> +        binding.logoutIV.setOnClickListener {
I prefer leaving an empty line between setters (same for the observers). It makes the code a bit clearer imo

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/adapter/RideHistoryViewHolder.kt
> +        binding.distanceTV.text = "${rideHistoryItem.distance} km"
Use string templates for formatting

2022-09-28 05:28 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/presentation/menu/viewmodel/MenuViewModel.kt
> +                Log.e("ERROR", e.message.toString())
Show the error to the user

2022-09-29 10:50 UTC, tapp-hadaralex approved these changes
Fix the 1 comment and you can merge.

2022-09-29 10:50 UTC, tapp-hadaralex commented on app/src/main/java/com/internship/move/presentation/menu/adapter/RideHistoryViewHolder.kt
> +        binding.distanceTV.text = "${rideHistoryItem.distance} km"
use resource strings

2022-09-29 11:20 UTC, merged